### ISSUE TITLE
如何启动本项目

### ISSUE THREAD

**Issue by tornado404** [wuyuanwuhui99/springboot-app-service#2]
代码包挺清晰的，sql文件也有，配置也知道。但是我不知道怎么启动它。按照spring boot的习惯，应该会有一个main app类用于启动；如果是多个子module，应该会有一个到多个能用于启动

# 问题描述
这个项目里，多了一个注册中心后，我完全不知道该从哪个mian class启动，而且使用idea打开后，所有的main类都标红，无法执行run

# 请求
是否可以在ReadMe中新增一个启动使用说明，大致描述一下启动命令

**Comment by tornado404** [comment]
已经看到了启动说明了，非常赞

**Comment by show110695** [comment]
> 已经看到了启动说明了，非常赞

哪里有启动说明

**Comment by tornado404** [comment]
> > 已经看到了启动说明了，非常赞
> 
> 哪里有启动说明

应该是`mvnw.cmd`文件，你看看内容
